spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.254:8848
        ip: localhost
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: api
          uri: lb://api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1