spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.254
        ip: localhost
  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: http://localhost:9000/auth
          jwk-set-uri: http://localhost:9000/auth/oauth2/jwks