spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.254
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://127.0.0.1:9100
          jwk-set-uri: http://127.0.0.1:9100/oauth2/jwks